trigger:
- master

resources:
- repo: self


variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self
      lfs: true
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'rtuitlab connection by admin'
        repository: 'rtuitlab/files'
        command: 'buildAndPush'
        Dockerfile: 'Dockerfile'
        tags: |
          $(tag)
          latest
- stage: UpdateService
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    environment: production
    strategy:
      runOnce:
        deploy:
          steps:
            - download: none
            - task: SSH@0
              inputs:
                sshEndpoint: 'swarm manager'
                runOptions: 'commands'
                commands: 'docker service update --image rtuitlab/files:$(tag) files_server'
                readyTimeout: '20000'